# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2.16.0

      - name: Install dependencies
        run: flutter pub get --no-example

      - name: Analyze project source
        working-directory: ./lib
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
